### ISSUE TITLE
use 'lon' instead of 'lng'

### ISSUE THREAD

**Issue by tshepang** [booyaa/wifilocation#1]
I say this only because I haven't seen *longitude* shortened to *lng*.

**Comment by booyaa** [comment]
Unfortunately this would break the parsing response from [API ](https://developers.google.com/maps/documentation/geolocation/intro#responses) to google maps.

Not sure why Google went down this route, but turns out there's no official consensus on this: https://gis.stackexchange.com/questions/24690/difference-between-lon-and-lng

I will add a comment to the Struct to explain the use of `lng` over `lon`.

Thanks.

**Comment by tshepang** [comment]
thanks for that, I did not know

**Comment by Boscop** [comment]
Rust-geo also uses Point::lng():
https://georust.github.io/rust-geo/geo/struct.Point.html#method.lng
